baseURL: "https://vinceyordanov.netlify.app"
languageCode: "en-us"
title: "Professional Profile - Vince Yordanov"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    backgroundColor: "#fff"
    secondaryBackgroundColor: "#fff"
  #   textColor:
  #   secondaryTextColor:
     
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Professional Profile & Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Vince Yordanov"
    subtitle: "Data Engineer"
    content: |- 
      I'm a young professional, passionate about creating data-driven solutions that have a positive impact on 
      the performance of businesses. I have a background in mathematics and machine learning, and I take particular interest in 
      the development of data & AI-intensive applications, especially in the realm of finance. I am currently working as 
      a data engineer at IKEA in Malmö, Sweden, where I am part of a team that's developing the company's data tracking & analytics 
      capabilities. Please have a look at my credentials and some projects that I have worked on below. 

    image: /images/imgg.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "https://online.flippingbook.com/view/11333224/"
      #url: "https://easyupload.io/pgxp4y"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/vinceyordanov
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/vinceyordanov
  
  # Achievements
  achievements:
    enable: true
    title: "My Areas of Expertise"
    items:
      - title: Machine Learning
        content: I build, train and deploy robust ML models with application in various fields.
      - title: Data Engineering
        content: I build complex ETL pipelines in order to facilitate high-volume batch and stream data processing.
      - title: Data Analytics
        content: I create insightful analytics dashboards to highlight important aspects in a business model.
      - title: Cloud Infrastructure
        content: I manage and provision cloud-based / servereless infrastructure, and regularly deploy applications to Google's cloud platform. 
      - title: Programming
        content: I write code that has impact and generates revenue. Some of the languages I work with on a daily basis include R, Python, SQL and JavaScript.
 
  # About
  about:
    enable: false
    title: "About Me"
    image: "/images/me.png"
    roundImage: true
    bottomImage: 
      enable: true
    
    content: |-
      I am 26 years old, born in Sofia, Bulgaria and raised in Ottawa, Canada. Since 2021, I have been living in Malmö, Sweden. I have a passion for 
      big data and creating software, especially when it comes to the stock market and finance. My start-up vyAnalytics focuses on delivering 
      robust and scalable AI-driven trading algorithms as well as NLP models that analyze rapidly changing financial sentiment, in the hopes of 
      helping retail investors make informed decisions about their investments. I also work for IKEA, where I am helping the company become the 
      industry leader in the digitalization of home-furnishing.

    skills:
      enable: true
      title: "Here are the programming languages I use in my work on a daily-basis:"
      items:
        - "R"
        - "Python"
        - "JavaScript"
        - "SQL"
        - "YAML"


  # Experience
  experience:
    enable: true
    title: "My Experience"
    items:
      - job: "Data Engineer"
        company: "IKEA"
        companyUrl: "https://ikea.com"
        date: "April 2022 - present"
        content: |-
          Responsibilities
            - Build ETL pipelines to handle the processing of hundreds of millions of data records  coming daily from the IKEA web & app in over 50 markets worldwide.
            - Implement CI/CD system using GitHub Actions and Terraform to facilitate efficient product lifecycle methodology, introduce semantic versioning and reduce risk of major pipeline failures.
            - Enhance computational performance of existing SQL queries through modularization of code, reducing BigQuery analytics cost by more than 30%.
            - Help design an in-house data collection system to replace Google Analytics system & uphold IKEAs GDPR compliance.
            - Write and publish reports to help make key make-or-buy decision for data-profiling and data quality monitoring tools.
        info:
          enable: false  
        
      - job: "Data & Machine Learning Engineer"
        company: "vyAnalytics"
        companyUrl: "https://vyanalytics.net"
        date: "June 2021 - present"
        content: |-
          Responsibilities
            - Build ETL pipeline to facilitate processing of large volumes of real time bid/ask/trade NASDAQ stock market data.
            - Build and deploy robust VertexAI pipelines to generate prediction of stock price directions.
            - Integrate NLP models into AI pipeline to automate financial sentiment analysis of various NASDAQ company earnings reports.
            - Create and deploy AI-driven web application aimed to provide hospitals in the USA with real-time risk assessment of ICU overcapacity during the Covid-19 pandemic.
        featuredLink:
          enable: true
          name: "Web App Demo"
          url: "https://chicago.shinyapps.io/CoronaTrackApp"
        info:
          enable: false
          content: I founded an AI startup called vyAnalytics, and while progress is slow, I am still actively working on development of new products.


      - job: "Data Analyst"
        company: "Alstom Group - Canada"
        companyUrl: "https://www.alstom.com/"
        date: "Jan 2020 - Sep 2020"
        content: |-
          Responsibilities
            - Automate the process of collecting data on software errors, mechanical problems, and system failures for trains in Ottawas Light Rail Transit system.
            - Wrote SQL scripts to extract business insights and key metrics on train performance.
            - Implement ARIMA time-series models to forecast mechanical failures for all of Ottawas LRT trains.
            - Build and maintain dashboards to visualize key metrics and present KPIs to city officials and key stakeholders of Alstom Group in Canada.
        info:
          enable: false

      - job: "Data Science Intern"
        company: "City of Ottawa"
        companyUrl: "https://www.ottawa.ca/"
        date: "May 2019 - Sep 2019"
        content: |-
          Responsibilities
            -	Wrote code to sort through and categorize a massive dataset containing 7 years worth of transportation data.  
            -	Implemented a k-nearest neighbors algorithm to interpolate and fill in missing data entries.
            -	Usied moving average and signal extraction techniques to filter out noise and make data more informative. 
            -	Generated visualizations for 7 time series corresponding to data for the years 2011-2018  
            -	Forecasted future levels of bicycle transportation via an ARIMA model, chosen after careful consideration.  
            -	Analyzed cyclical nature and seasonal trends of biker data using frequency-domain analyses.   
            -	Attended meetings, taking part in discussions with city officials and presenting work.  
            -	Played a key role in organizing the work with my team members.  
        info:
          enable: false
          content: As a data science intern for the City of Ottawa, I was involved in working on an ongoing project for Ottawas Master Transportation Plan with a team of 3 other students. The end goal was to provide city officials with accurate estimates and predictions regarding commuting in the city via bicycles – in hopes of helping them build infrastructure that caters to cyclists and promotes eco-friendly transportation

      - job: "Junior Analyst"
        company: "Shared Services Canada"
        companyUrl: "https://www.canada.ca/en/shared-services.html/"
        date: "May 2017 - Sep 2017"
        content: |-
          Responsibilities
            - Monitored a cloud fax server used by Bank of Canada for secure transactions.
            - Used Apache and WebSphere to maintain, update and troubleshoot technical issues for WebServers.
            - Debugged and inspected java code associated with Webservers used by the Federal Government.
            - Addressed support tickets opened by other government employees.
            - Wrote simple scripts to create over 50 online ports for easier access to online servers by other team-members
            - Wrote documentation for future student interns and employees.
            - Gave monthly presentations at team meetings and attended student networking events.
        info:
          enable: false
  
  # Education
  education:
    enable: true
    title: "Education"
    items:
      - job: "McMaster University"
        company: "MSc. Mathematics & Statistics"
        companyUrl: "https://mcmaster.ca"
        date: "Sep 2020 - May 2021"
        content: |-
          Highlights
            -	Successful completion of a one-year competitive MSc. Program 
            -	Entry and departmental scholarships based on academic excellence.   
            -	Completion of independent research project, including successful defense in front of peers and faculty. 
            -	Over 200 hours of hosting lectures and tutorials for statistics courses with over 300 students.  
        
        
          Academic Research
            - My graduate research focused on studying and proving the superiority of intrinsic conditional autoregressive (ICAR) Poisson models over
              regular Generalized Linear Mixed Models when fitting spatially correlated data. Specifically, my investigation shows that for 
              geospatial homicide data (output) & socioeconomic indicators in Chicagos neighbourhoods (input), the CAR model outperforms non-spatial 
              GLMMs on almost every metric. A secondary conclusion that can be drawn from the paper is that Machine Learning can have tremendous 
              multifaceted benefits in helping law enforcemenet tackle violent crime. 
        featuredLink:
          enable: true
          name: "Research Paper"
          url: "https://online.flippingbook.com/view/695367507/"      
          
      - job1: "Carleton University"
        company1: "Honours Bachelor of Mathematics"
        companyUrl1: "https://carleton.ca"
        date1: "Sep 2016 - Jan 2020"
        content1: |-
          Highlights
            - Active member of Carletons Mathematics Society. 
            - Founder of the Bulgarian Students in Carleton Society, helping raise money and hosting events.
            - Entry and departmental scholarships based on academic excellence.
            - Data Science intern for City of Ottawa (worked on city master transportation plan)
            


  
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hospital ICU Overcapacity Risk
        content: A web application designed to help hospitals have real-time risk assessment of ICU bed shortages during Covid-19 patient spikes.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: "https://chicago.shinyapps.io/CoronaTrackApp"
        badges:
          - "R"
          - "JavaScript"
          - "ShinyApps"
        links:
          - icon: fab fa-github
            url: https://github.com/vinceyordanov
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Portfolio Analytics
        content: A web application built to provide actionable insights to retail investors, and help them make informed decisions about their portfolios.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://chicago.shinyapps.io/testdboard
        badges:
          - "R"
          - "JavaScript"
          - "ShinyApps"
        links:
          - icon: fab fa-github
            url: https://github.com/vinceyordanov

      - title: Chicago Crime Statistics
        content: A dashboard designed to track and provide crime forecasts for the city of Chicago in real-time.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo
          link: https://hugo-profile-2.netlify.app
        badges:
          - "R"
          - "JavaScript"
          - "ShinyApps"
          - "BigQuery"
        links:
          - icon: fab fa-github
            url: https://github.com/vinceyordanov

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: vinceyordanov@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: false

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
